# Generated by Django 2.0.7 on 2018-07-19 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_holder',
            field=models.ForeignKey(blank=True, help_text='Entity that has an account with Encamp with which this user is associated.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.AccountHolder'),
        ),
    ]
