# Generated by Django 2.0.7 on 2018-07-18 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20180718_1609'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='encampuser',
            options={'ordering': ['last_name', 'first_name']},
        ),
        migrations.RemoveField(
            model_name='encampuser',
            name='name',
        ),
        migrations.AddField(
            model_name='encampuser',
            name='first_name',
            field=models.CharField(default='Daniel', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='encampuser',
            name='last_name',
            field=models.CharField(default='Smedema', max_length=255),
            preserve_default=False,
        ),
    ]
