# Generated by Django 2.0.7 on 2018-07-18 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20180718_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='encampuser',
            name='account_holder',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.AccountHolder'),
        ),
    ]
