# Generated by Django 2.0.7 on 2018-07-19 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_encampuser_account_holder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encampuser',
            name='full_address_raw',
            field=models.CharField(blank=True, editable=False, max_length=511, null=True),
        ),
    ]
