# Generated by Django 2.0.7 on 2018-07-19 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='record_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='people_person_owned_set', to='accounts.AccountHolder'),
        ),
    ]
