# Generated by Django 2.0.7 on 2018-07-19 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_auto_20180719_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='full_address_raw',
            field=models.CharField(blank=True, editable=False, max_length=511, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='record_owner',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='people_person_owned_set', to='accounts.AccountHolder'),
        ),
    ]
